### ISSUE TITLE
clam_loci error

### ISSUE THREAD

**Issue by cnloves** [harvardinformatics/shortRead_mapping_variantCalling#268]
First of all, thank you for such a wonderfully useful tool! 

We have been working with snparcher for a while now and are running into a new issue with the most recent installation downloads and runs. 

I am running snparcher with the most recent version of snakemake: v.9.10.0 and a recent snparcher download on a test dataset of two samples, with ~30x coverage. 

Originally the clam_loci rule oom killed the job. But after increasing the rule's memory allottment, I am still encountering clam_loci errors. I have altered the memory allotted, started from a brand new snparcher installation and download, attempted running with an older version of snakemake (v8.27.1) and have attempted running the pipeline on a couple different test samples and genomes, all to no avail… (see error below)

> …Error in rule clam_loci:
>     message: SLURM-job '725179' failed, SLURM status is: 'FAILED'. For further error details see the cluster/cloud log and the log files of the involved rule(s).
>     jobid: 25
>     input: results/Test5/callable_sites/SB1.per-base.d4.gz, results/Test5/callable_sites/SB2.per-base.d4.gz, results/Test5/callable_sites/SB1.per-base.d4.gz.gzi, results/Test5/callable_sites/SB2.per-base.d4.gz.gzi, results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv
>     output: results/Test5/callable_sites/Test5_SB_test/callable_sites.d4, results/Test5/callable_sites/Test5_SB_test/callable_sites.bed, results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed
>     log: logs/Test5/covbed/Test5_SB_test.txt, /snpArcher/.snakemake/slurm_logs/rule_clam_loci/Test5_Test5_SB_test/725179.log (check log file(s) for error details)…

The issue appears to be that the clam_loci rule errors out and attempts to restart 3 times – finally ending in an error. Despite the error however, I end up with output bed and vcf files, suggesting that the clam_loci error did not prevent snparcher from completing?  While investigating the log files, there is a message at the end of the run in the covbed log that says:

> clam version: 0.2.1 arguments supplied: clam loci -t 16 --bed --thresholds-file /results/Test5/callable_sites/Test5_test_callable_sites_thresholds.tsv -o /results/Test5/callable_sites/Test5_test results/Test5/callable_sites/ERR3494841.per-base.d4.gz results/Test5/callable_sites/ERR1990157.per-base.d4.gz
> [2025-09-16T18:20:41Z INFO  clam::loci::io] D4 file writing complete.
> WARNING: more than 2147483647 records; some functionality may not work!

I would 1) like to get clam_loci working and 2) know whether the output files are complete and reliable without the inclusion of the clam_loci rule? Any suggestions and help would be super helpful! Thanks!!

A copy of a slurm_log output /slurm_logs/rule_clam_loci/Test5_Test5_SB_test//725518.log - if it is also helpful is:

> /Test5/snpArcher/workflow/rules/common.smk:14: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
>   from pkg_resources import parse_version
> snpArcher: Using Snakemake 9.10.0
> host: della-h14n8
> Building DAG of jobs...
> Using shell: /usr/bin/bash
> Provided remote nodes: 1
> Select jobs to execute...
> Execute 1 jobs...
> 
> [Wed Sep 17 18:28:42 2025]
> rule clam_loci:
>     input: results/Test5/callable_sites/SB1.per-base.d4.gz, results/Test5/callable_sites/SB2.per-base.d4.gz, results/Test5/callable_sites/SB1.per-base.d4.gz.gzi, results/Test5/callable_sites/SB2.per-base.d4.gz.gzi, results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv
>     output: results/Test5/callable_sites/Test5_SB_test/callable_sites.d4, results/Test5/callable_sites/Test5_SB_test/callable_sites.bed, results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed
>     log: logs/Test5/covbed/Test5_SB_test.txt
>     jobid: 0
>     benchmark: benchmarks/Test5/covbed/Test5_SB_test_benchmark.txt
>     reason: Forced execution
>     wildcards: refGenome=Test5, prefix=Test5_SB_test
>     threads: 4
>     resources: mem_mb=40000, mem_mib=38147, disk_mb=1176, disk_mib=1122, tmpdir=<TBD>, mem_mb_reduced=3600, slurm_account=campbellstaton, runtime=4320, cpus_per_task=4
> /Test5/snpArcher/workflow/rules/common.smk:14: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
>   from pkg_resources import parse_version
> snpArcher: Using Snakemake 9.10.0
> host: della-h14n8
> Building DAG of jobs...
> Using shell: /usr/bin/bash
> Provided cores: 4
> Rules claiming more threads will be scaled down.
> Select jobs to execute...
> Execute 1 jobs...
> 
> [Wed Sep 17 18:28:44 2025]
> localrule clam_loci:
>     input: results/Test5/callable_sites/SB1.per-base.d4.gz, results/Test5/callable_sites/SB2.per-base.d4.gz, results/Test5/callable_sites/SB1.per-base.d4.gz.gzi, results/Test5/callable_sites/SB2.per-base.d4.gz.gzi, results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv
>     output: results/Test5/callable_sites/Test5_SB_test/callable_sites.d4, results/Test5/callable_sites/Test5_SB_test/callable_sites.bed, results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed
>     log: logs/Test5/covbed/Test5_SB_test.txt
>     jobid: 0
>     benchmark: benchmarks/Test5/covbed/Test5_SB_test_benchmark.txt
>     reason: Forced execution
>     wildcards: refGenome=Test5, prefix=Test5_SB_test
>     threads: 4
>     resources: mem_mb=40000, mem_mib=38147, disk_mb=1176, disk_mib=1122, tmpdir=/tmp, mem_mb_reduced=3600, slurm_account=campbellstaton, runtime=4320, cpus_per_task=4
> Activating conda environment: .snakemake/conda/36828144e594cf0a7fc3ff7f7478326f_
> /usr/bin/bash: line 2: 2059147 Killed                  clam loci -t 4 --bed --thresholds-file results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv -o results/Test5/callable_sites/Test5_SB_test results/Test5/callable_sites/SB1.per-base.d4.gz results/Test5/callable_sites/SB2.per-base.d4.gz 2> logs/Test5/covbed/Test5_SB_test.txt
> RuleException:
> CalledProcessError in file "/Test5/snpArcher/workflow/rules/cov_filter.smk", line 71:
> Command 'source /home/cl5291/miniforge3/bin/activate '/Test5/snpArcher/.snakemake/conda/36828144e594cf0a7fc3ff7f7478326f_'; set -euo pipefail;  
>         clam loci -t 4 --bed --thresholds-file results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv -o results/Test5/callable_sites/Test5_SB_test results/Test5/callable_sites/SB1.per-base.d4.gz results/Test5/callable_sites/SB2.per-base.d4.gz 2> logs/Test5/covbed/Test5_SB_test.txt
>         bedtk merge results/Test5/callable_sites/Test5_SB_test/callable_sites.bed > results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         cp results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed results/Test5/callable_sites/Test5_SB_test/callable_sites.bed 2>> logs/Test5/covbed/Test5_SB_test.txt' returned non-zero exit status 137.
> [Wed Sep 17 18:29:20 2025]
> Error in rule clam_loci:
>     message: None
>     jobid: 0
>     input: results/Test5/callable_sites/SB1.per-base.d4.gz, results/Test5/callable_sites/SB2.per-base.d4.gz, results/Test5/callable_sites/SB1.per-base.d4.gz.gzi, results/Test5/callable_sites/SB2.per-base.d4.gz.gzi, results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv
>     output: results/Test5/callable_sites/Test5_SB_test/callable_sites.d4, results/Test5/callable_sites/Test5_SB_test/callable_sites.bed, results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed
>     log: logs/Test5/covbed/Test5_SB_test.txt (check log file(s) for error details)
>     conda-env: /Test5/snpArcher/.snakemake/conda/36828144e594cf0a7fc3ff7f7478326f_
>     shell:
>         
>         clam loci -t 4 --bed --thresholds-file results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv -o results/Test5/callable_sites/Test5_SB_test results/Test5/callable_sites/SB1.per-base.d4.gz results/Test5/callable_sites/SB2.per-base.d4.gz 2> logs/Test5/covbed/Test5_SB_test.txt
>         bedtk merge results/Test5/callable_sites/Test5_SB_test/callable_sites.bed > results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         cp results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed results/Test5/callable_sites/Test5_SB_test/callable_sites.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         
>         (command exited with non-zero exit code)
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look below for error messages
> [Wed Sep 17 18:29:20 2025]
> Error in rule clam_loci:
>     message: None
>     jobid: 0
>     input: results/Test5/callable_sites/SB1.per-base.d4.gz, results/Test5/callable_sites/SB2.per-base.d4.gz, results/Test5/callable_sites/SB1.per-base.d4.gz.gzi, results/Test5/callable_sites/SB2.per-base.d4.gz.gzi, results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv
>     output: results/Test5/callable_sites/Test5_SB_test/callable_sites.d4, results/Test5/callable_sites/Test5_SB_test/callable_sites.bed, results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed
>     log: logs/Test5/covbed/Test5_SB_test.txt (check log file(s) for error details)
>     conda-env: /Test5/snpArcher/.snakemake/conda/36828144e594cf0a7fc3ff7f7478326f_
>     shell:
>         
>         clam loci -t 4 --bed --thresholds-file results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv -o results/Test5/callable_sites/Test5_SB_test results/Test5/callable_sites/SB1.per-base.d4.gz results/Test5/callable_sites/SB2.per-base.d4.gz 2> logs/Test5/covbed/Test5_SB_test.txt
>         bedtk merge results/Test5/callable_sites/Test5_SB_test/callable_sites.bed > results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         cp results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed results/Test5/callable_sites/Test5_SB_test/callable_sites.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         
>         (command exited with non-zero exit code)
> Storing output in storage.
> WorkflowError:
> At least one job did not complete successfully.
> slurmstepd: error: Detected 1 oom_kill event in StepId=725179.0. Some of the step tasks have been OOM Killed.
> srun: error: della-h14n8: task 0: Out Of Memory
> srun: Terminating StepId=725179.0
> [Wed Sep 17 18:29:21 2025]
> Error in rule clam_loci:
>     message: None
>     jobid: 0
>     input: results/Test5/callable_sites/SB1.per-base.d4.gz, results/Test5/callable_sites/SB2.per-base.d4.gz, results/Test5/callable_sites/SB1.per-base.d4.gz.gzi, results/Test5/callable_sites/SB2.per-base.d4.gz.gzi, results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv
>     output: results/Test5/callable_sites/Test5_SB_test/callable_sites.d4, results/Test5/callable_sites/Test5_SB_test/callable_sites.bed, results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed
>     log: logs/Test5/covbed/Test5_SB_test.txt (check log file(s) for error details)
>     conda-env: /Test5/snpArcher/.snakemake/conda/36828144e594cf0a7fc3ff7f7478326f_
>     shell:
>         
>         clam loci -t 4 --bed --thresholds-file results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv -o results/Test5/callable_sites/Test5_SB_test results/Test5/callable_sites/SB1.per-base.d4.gz results/Test5/callable_sites/SB2.per-base.d4.gz 2> logs/Test5/covbed/Test5_SB_test.txt
>         bedtk merge results/Test5/callable_sites/Test5_SB_test/callable_sites.bed > results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         cp results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed results/Test5/callable_sites/Test5_SB_test/callable_sites.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         
>         (command exited with non-zero exit code)
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look below for error messages
> [Wed Sep 17 18:29:21 2025]
> Error in rule clam_loci:
>     message: None
>     jobid: 0
>     input: results/Test5/callable_sites/SB1.per-base.d4.gz, results/Test5/callable_sites/SB2.per-base.d4.gz, results/Test5/callable_sites/SB1.per-base.d4.gz.gzi, results/Test5/callable_sites/SB2.per-base.d4.gz.gzi, results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv
>     output: results/Test5/callable_sites/Test5_SB_test/callable_sites.d4, results/Test5/callable_sites/Test5_SB_test/callable_sites.bed, results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed
>     log: logs/Test5/covbed/Test5_SB_test.txt (check log file(s) for error details)
>     conda-env: /Test5/snpArcher/.snakemake/conda/36828144e594cf0a7fc3ff7f7478326f_
>     shell:
>         
>         clam loci -t 4 --bed --thresholds-file results/Test5/callable_sites/Test5_SB_test_callable_sites_thresholds.tsv -o results/Test5/callable_sites/Test5_SB_test results/Test5/callable_sites/SB1.per-base.d4.gz results/Test5/callable_sites/SB2.per-base.d4.gz 2> logs/Test5/covbed/Test5_SB_test.txt
>         bedtk merge results/Test5/callable_sites/Test5_SB_test/callable_sites.bed > results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         cp results/Test5/callable_sites/Test5_SB_test/callable_sites_temp.bed results/Test5/callable_sites/Test5_SB_test/callable_sites.bed 2>> logs/Test5/covbed/Test5_SB_test.txt
>         
>         (command exited with non-zero exit code)
> Storing output in storage.
> WorkflowError:
> At least one job did not complete successfully.

**Comment by TeresaPegan** [comment]
This is also happening to me this week, and I'm having issues with even higher memory allocations. Here's the sacct info from the clam_loci job in my latest attempt:

```
JobID           JobName     MaxRSS     ReqMem      State 
------------ ---------- ---------- ---------- ---------- 
3631364      f57e78cd-+                  125G     FAILED 
3631364.bat+      batch    138428K                FAILED 
3631364.ext+     extern                        COMPLETED 
3631364.0    python3.11 130959604K            OUT_OF_ME+ 
```


What I have in `snpArcher/workflow-profiles/default/config.yaml`:

```
# To customize a rule, copy one of the example blocks above, paste it under "set-resources:",
# replace the rule name with your target rule, and adjust the resource parameters as needed.
set-resources:
   # Example 1: Increase memory for bam2gvcf rule
  callable_bed:
    mem_mb: attempt * 128000  # Customize memory allocation
    mem_mb_reduced: (attempt * 64000) * 0.9  # Customize Java memory allocation

  clam_loci:
    mem_mb: attempt * 128000  # Customize memory allocation
    mem_mb_reduced: (attempt * 64000) * 0.9  # Customize Java memory allocation
```

I guess I'll just keep trying higher...? This is a situation where I've aligned only 20 individuals, each sequenced at about 20x, to a 1 GB reference genome.

**Comment by TeresaPegan** [comment]
Throwing more memory at clam_loci did end up allowing it to complete for me:
```
JobID           JobName     MaxRSS     ReqMem      State 
------------ ---------- ---------- ---------- ---------- 
3721857      9ca3d44d-+               184000M  COMPLETED 
3721857.bat+      batch     95456K             COMPLETED 
3721857.ext+     extern                        COMPLETED 
3721857.0    python3.11 178602232K             COMPLETED 
```

**Comment by tsackton** [comment]
@TeresaPegan Good to here. I'm going to keep this issue open for now but it seems like this is something that probably needs to be fixed upstream in clam

**Comment by cademirch** [comment]
@tsackton  I think this was fixed when clam moved to zarr.

**Comment by tsackton** [comment]
We now pin clam >= 1.1 though. @TeresaPegan are you using the latest snpArcher version or an old version? Can you check which version of clam this is using?

**Comment by cademirch** [comment]
I suspect its v1 snpArcher given their profile:

> What I have in `snpArcher/workflow-profiles/default/config.yaml`:
> 
> ```
> # To customize a rule, copy one of the example blocks above, paste it under "set-resources:",
> # replace the rule name with your target rule, and adjust the resource parameters as needed.
> set-resources:
>    # Example 1: Increase memory for bam2gvcf rule
>   callable_bed:
>     mem_mb: attempt * 128000  # Customize memory allocation
>     mem_mb_reduced: (attempt * 64000) * 0.9  # Customize Java memory allocation
> 
>   clam_loci:
>     mem_mb: attempt * 128000  # Customize memory allocation
>     mem_mb_reduced: (attempt * 64000) * 0.9  # Customize Java memory allocation
> ```
> 
> I guess I'll just keep trying higher...? This is a situation where I've aligned only 20 individuals, each sequenced at about 20x, to a 1 GB reference genome.

**Comment by TeresaPegan** [comment]
Yeahhh I am on the older version of snpArcher. I have to run it on another dataset, I will upgrade to the latest and let you know if I still see the clam_loci job using so much memory.

I had been reading #272 and I did have to force snparcher back to clam version 0.2.1 for the same reason described there. I was not sure if it was a good idea to update snparcher itself midway through an unfinished run of the pipeline, so I made the clam fix instead, but in hindsight maybe all of these clam problems are taken care of with the latest version of snparcher.

**Comment by tsackton** [comment]
Yeah I think all the clam problems are fixed with v2. v2 uses a different sample sheet format and a different config file so it is a bit of a pain to switch half way. But possible, if you decide to go that route. See [here](https://snparcher.readthedocs.io/en/latest/v2-migration.html).
